<!-- <footer class="page-footer"> -->
<div class="footer content">
   <div class="links">
      <div class="widget block block-static-block">
         <h4>About Us</h4>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            sed do eiusmod tempor incididunt ut labore et dolore 
            magna aliqua. Ut enim ad minim veniam, quis nostrud
            exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in 
            voluptate velit esse cillum dolore eu fugiat nulla pariatur.
         </p>
      </div>
   </div>
   <div class="footer links">
      <h4>Quick Access</h4>
         <ul>
            <li class="nav item"><a href="#">Fashion </a></li>
            <li class="nav item"><a href="#">Shoes </a></li>
            <li class="nav item"><a href="#">Mobile Phones </a></li>
            <li class="nav item"><a href="#">Bags </a></li>
            <li class="nav item"><a href="#">Body care </a></li>
            <li class="nav item"><a href="#">Electronics </a></li>
            <li class="nav item"><a href="#">New Arrival </a></li>
         </ul>
   </div>
</div>
<!-- </footer> -->